# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: my-permit.my-organization

  version: '1.0.0'
  description: The my-permit credential issued by my-org-full-name
  path: /my-organization/my-permit

  attributes:
    - corp_num
    - legal_name
    - permit_id
    - permit_type
    - permit_issued_date
    - permit_status
    - effective_date

### eof ###

