default:
  APPLICATION_URL_VONX: $APPLICATION_URL/regov/kyc
  TEMPLATE_PATH: ../templates

  TOB_API_URL: http://3.0.165.97:8080/api/v2/
  TOB_APP_URL: http://3.0.165.97:8080

  WALLET_SEED_VONX: regov_kyc_key_000000000000000000

  INDY_GENESIS_URL: INDY_GENESIS_URL: http://3.0.165.97:9000/genesis

  LEDGER_PROTOCOL_VERSION: "1.6"
  AUTO_REGISTER_DID: true

### eof ###
