default:
  APPLICATION_URL_VONX: $APPLICATION_URL/regov/kyc
  TEMPLATE_PATH: ../templates

  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080

  WALLET_SEED_VONX: regov_kyc_0000000000000000

  INDY_GENESIS_URL: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis

  LEDGER_PROTOCOL_VERSION: "1.6"
  AUTO_REGISTER_DID: false

### eof ###
